version: '3.3'

services:
  auth:
    image: registry.ignitial.io/ignitial/auth:${APP_VERSION}
    container_name: auth
    volumes:
      - ${PWD}/server:/opt/auth/server
      - ${PWD}/node_modules:/opt/auth/node_modules
    ports:
      - ${IIOS_DOCKER_EXPORTED_PORTS}
    environment:
      - IIOS_REDIS_HOST=redis
      - IIOS_NAMESPACE=${IIOS_NAMESPACE}
      - IIOS_SERVER_HOST=0.0.0.0
      - IIOS_SERVER_PORT=${IIOS_SERVER_PORT}
    networks:
      infra:

networks:
  infra:
    external: true
